add a build trigger

diff --git a/.github/workflows/cross_compile.yml b/.github/workflows/cross_compile.yml
--- a/.github/workflows/cross_compile.yml
+++ b/.github/workflows/cross_compile.yml
@@ -49,3 +49,14 @@ jobs:
             wget -O target/release/oliviabot https://github.com/RocketRace/oliviabot/releases/latest/download/oliviabot
             chmod +x target/release/oliviabot
             touch .watch-trigger
+            rm .build-success
+            timeout=120
+            while [ ! -f .build-success ]; do
+              if [ "$timeout" == 0 ]; then
+                echo "Bot failed to launch!"
+                exit 1
+              fi
+              sleep 1
+              ((timeout--))
+            done
+
